#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Brave-browser desktop='^3'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Steam desktop='^5'
bspc rule -a Deadbeef desktop='^6'

# autostart
nm-applet &
dunst &
sxhkd &
redshift &
xrandr --output eDP1 --mode 1920x1080 && \
    feh --bg-scale Shelf/img/wallpaper
setxkbmap -layout us,ru -option grp:caps_toggle
$HOME/.config/polybar/launch.sh &
