#! /bin/sh

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

########### RULES ###########
# Browsers
bspc rule -a Brave-browser desktop='^3'
bspc rule -a Min desktop='^3'
bspc rule -a firefox desktop='^3'
# Social
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a zoom desktop='^4'
bspc rule -a discord desktop='^4'
# Fun
bspc rule -a Steam desktop='^5'
# Daemons
bspc rule -a Deadbeef desktop='^6'

bspc rule -a Typora state=pseudo_tiled rectangle=800x600+0+0
bspc rule -a Todoist state=pseudo_tiled rectangle=800x600+0+0
bspc rule -a pomotroid state=pseudo_tiled
bspc rule -a MEGAsync state=floating

######### AUTOSTART #########
copyq &
nm-applet &
dunst &
picom &
sxhkd &
redshift &
xrandr --output eDP1 --mode 1920x1080 && walp -r
setxkbmap -layout us,ru -option grp:caps_toggle
xset s off
$(cat $HOME/.config/polybar/current) &
megasync &
